// Package missioncontrol provides the database layer and business logic for the
// Mission Control product-autopilot engine embedded in the PicoClaw launcher.
//
// The planning package handles AI-assisted task planning: generating questions,
// processing answers, and finalizing planning specs.
package missioncontrol

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"

	"github.com/google/uuid"
)

// ExtractJSON extracts JSON from a response that might have markdown code blocks
// or surrounding text. It tries multiple strategies:
//  1. Direct parse
//  2. Markdown code block (```json ... ```)
//  3. JSON embedded in text (first { to last })
func ExtractJSON(text string) map[string]any {
	text = strings.TrimSpace(text)

	// 1. Try direct parse
	var result map[string]any
	if err := json.Unmarshal([]byte(text), &result); err == nil {
		return result
	}

	// 2. Try markdown code block (greedy)
	codeBlockRe := regexp.MustCompile("(?s)```(?:json)?\\s*(.*?)```")
	matches := codeBlockRe.FindStringSubmatch(text)
	if len(matches) > 1 {
		if err := json.Unmarshal([]byte(strings.TrimSpace(matches[1])), &result); err == nil {
			return result
		}
	}

	// 3. Try unclosed code block
	unclosedRe := regexp.MustCompile("(?s)```(?:json)?\\s*(\\{.*)")
	unclosed := unclosedRe.FindStringSubmatch(text)
	if len(unclosed) > 1 {
		candidate := strings.TrimSpace(unclosed[1])
		if err := json.Unmarshal([]byte(candidate), &result); err == nil {
			return result
		}
		// Try trimming from last brace
		lastBrace := strings.LastIndex(candidate, "}")
		if lastBrace > 0 {
			if err := json.Unmarshal([]byte(candidate[:lastBrace+1]), &result); err == nil {
				return result
			}
		}
	}

	// 4. Try to find JSON object (first { to last })
	firstBrace := strings.Index(text, "{")
	lastBrace := strings.LastIndex(text, "}")
	if firstBrace != -1 && lastBrace > firstBrace {
		if err := json.Unmarshal([]byte(text[firstBrace:lastBrace+1]), &result); err == nil {
			return result
		}
	}

	return nil
}

// PlanningQuestion represents a question generated during the planning phase.
type PlanningQuestion struct {
	ID           string `json:"id"`
	TaskID       string `json:"task_id"`
	Category     string `json:"category"`
	Question     string `json:"question"`
	QuestionType string `json:"question_type"`
	Options      string `json:"options"`
	Answer       string `json:"answer"`
	AnsweredAt   string `json:"answered_at,omitempty"`
	SortOrder    int    `json:"sort_order"`
}

// PlanningQuestionOption represents a single option in a planning question.
type PlanningQuestionOption struct {
	ID    string `json:"id"`
	Label string `json:"label"`
}

// planningQuestionRow is a helper for building spec markdown from answered questions.
type planningQuestionRow struct {
	Category string
	Question string
	Answer   string
}

// llmPlanningQuestion represents a question generated by the LLM.
type llmPlanningQuestion struct {
	Category     string   `json:"category"`
	Question     string   `json:"question"`
	QuestionType string   `json:"question_type"`
	Options      []string `json:"options"`
}

// GeneratePlanningQuestions creates planning questions for a task.
// First tries LLM generation, falls back to default questions if LLM is unavailable.
func GeneratePlanningQuestions(ctx context.Context, db *DB, taskID string, configPath string) ([]PlanningQuestion, error) {
	// Get task info
	var title, description string
	err := db.QueryRowContext(ctx,
		"SELECT title, COALESCE(description, '') FROM tasks WHERE id = ?", taskID,
	).Scan(&title, &description)
	if err != nil {
		return nil, fmt.Errorf("get task: %w", err)
	}

	// Try LLM-generated questions first
	var questions []PlanningQuestion
	llmQuestions, llmErr := generatePlanningQuestionsLLM(ctx, title, description, configPath)
	if llmErr != nil {
		// Fall back to default questions
		llmQuestions = defaultPlanningQuestions()
	}

	for i, q := range llmQuestions {
		id := uuid.New().String()
		optionsJSON, _ := json.Marshal(q.Options)
		pq := PlanningQuestion{
			ID:           id,
			TaskID:       taskID,
			Category:     q.Category,
			Question:     q.Question,
			QuestionType:  q.QuestionType,
			Options:      string(optionsJSON),
			SortOrder:    i,
		}

		_, err := db.ExecContext(ctx,
			"INSERT INTO planning_questions (id, task_id, category, question, question_type, options, sort_order) VALUES (?, ?, ?, ?, ?, ?, ?)",
			pq.ID, pq.TaskID, pq.Category, pq.Question, pq.QuestionType, pq.Options, pq.SortOrder,
		)
		if err != nil {
			return nil, fmt.Errorf("insert question: %w", err)
		}
		questions = append(questions, pq)
	}

	return questions, nil
}

// generatePlanningQuestionsLLM uses the LLM to generate context-aware planning questions.
func generatePlanningQuestionsLLM(ctx context.Context, title, description, configPath string) ([]llmPlanningQuestion, error) {
	prompt := fmt.Sprintf(`Generate 5 planning questions for a software task titled "%s". %s

For each question, provide:
- category: one of "goal", "audience", "scope", "technical", "design"
- question: the question text
- question_type: "multiple_choice"
- options: list of 4-5 option labels

Return a JSON array of questions. Example:
[{"category":"goal","question":"What is the primary goal?","question_type":"multiple_choice","options":["New feature","Bug fix","Refactor","Performance improvement"]}]

Generate questions that are specific to this task, not generic.`, title, func() string {
		if description != "" {
			return fmt.Sprintf("Description: %s", description)
		}
		return ""
	}())

	req := LLMRequest{
		Prompt:      prompt,
		System:      "You are a software project planning assistant. Generate relevant planning questions based on the task description. Always respond with valid JSON.",
		MaxTokens:   2048,
		Temperature: 0.5,
	}

	var result []llmPlanningQuestion
	err := CompleteJSONWithConfig(ctx, configPath, "", req, &result)
	if err != nil {
		return nil, fmt.Errorf("LLM planning question generation failed: %w", err)
	}

	if len(result) == 0 {
		return nil, fmt.Errorf("LLM returned empty questions")
	}

	// Validate and fix question types
	for i := range result {
		if result[i].QuestionType == "" {
			result[i].QuestionType = "multiple_choice"
		}
		if result[i].Category == "" {
			result[i].Category = "goal"
		}
		if len(result[i].Options) == 0 {
			result[i].Options = []string{"Option A", "Option B", "Option C"}
		}
	}

	return result, nil
}

// defaultPlanningQuestions returns hardcoded planning questions as a fallback.
func defaultPlanningQuestions() []llmPlanningQuestion {
	return []llmPlanningQuestion{
		{
			Category:     "goal",
			Question:     "What is the primary goal of this task?",
			QuestionType: "multiple_choice",
			Options:      []string{"New feature", "Bug fix", "Refactor", "Performance improvement", "Other"},
		},
		{
			Category:     "audience",
			Question:     "Who is the primary user or audience for this?",
			QuestionType: "multiple_choice",
			Options:      []string{"End users", "Developers", "Internal team", "Stakeholders", "Other"},
		},
		{
			Category:     "scope",
			Question:     "What is the expected scope of this task?",
			QuestionType: "multiple_choice",
			Options:      []string{"Small (hours)", "Medium (days)", "Large (weeks)", "Other"},
		},
		{
			Category:     "technical",
			Question:     "Are there any specific technical requirements or constraints?",
			QuestionType: "multiple_choice",
			Options:      []string{"Must use specific tech stack", "Must be backwards compatible", "Must be mobile responsive", "Must be accessible", "Other"},
		},
		{
			Category:     "design",
			Question:     "What design approach should be used?",
			QuestionType: "multiple_choice",
			Options:      []string{"Match existing design", "New design needed", "Minimal/sparse", "Rich/interactive", "Other"},
		},
	}
}

// ProcessPlanningAnswer records an answer to a planning question.
func ProcessPlanningAnswer(ctx context.Context, db *DB, taskID, questionID, answer string) error {
	_, err := db.ExecContext(ctx,
		"UPDATE planning_questions SET answer = ?, answered_at = datetime('now') WHERE id = ? AND task_id = ?",
		answer, questionID, taskID,
	)
	return err
}

// FinalizePlanningSpec creates a locked planning spec from answered questions.
func FinalizePlanningSpec(ctx context.Context, db *DB, taskID string) (string, error) {
	// Check if spec already exists
	var count int
	err := db.QueryRowContext(ctx,
		"SELECT COUNT(*) FROM planning_specs WHERE task_id = ?", taskID,
	).Scan(&count)
	if err != nil {
		return "", fmt.Errorf("check spec: %w", err)
	}
	if count > 0 {
		return "", fmt.Errorf("spec already locked")
	}

	// Get all answered questions
	rows, err := db.QueryContext(ctx,
		"SELECT category, question, answer FROM planning_questions WHERE task_id = ? AND answer IS NOT NULL ORDER BY sort_order",
		taskID,
	)
	if err != nil {
		return "", fmt.Errorf("get questions: %w", err)
	}
	defer rows.Close()

	var questions []planningQuestionRow
	for rows.Next() {
		var q planningQuestionRow
		if err := rows.Scan(&q.Category, &q.Question, &q.Answer); err != nil {
			continue
		}
		questions = append(questions, q)
	}

	// Get task info
	var title, description string
	db.QueryRowContext(ctx,
		"SELECT title, COALESCE(description, '') FROM tasks WHERE id = ?", taskID,
	).Scan(&title, &description)

	// Generate spec markdown
	specMarkdown := generateSpecMarkdown(title, description, questions)

	// Insert spec record
	specID := uuid.New().String()
	_, err = db.ExecContext(ctx,
		"INSERT INTO planning_specs (id, task_id, spec_markdown, locked_at) VALUES (?, ?, ?, datetime('now'))",
		specID, taskID, specMarkdown,
	)
	if err != nil {
		return "", fmt.Errorf("insert spec: %w", err)
	}

	// Update task status to inbox
	_, err = db.ExecContext(ctx,
		"UPDATE tasks SET description = ?, status = 'inbox', updated_at = datetime('now') WHERE id = ?",
		specMarkdown, taskID,
	)
	if err != nil {
		return "", fmt.Errorf("update task: %w", err)
	}

	return specID, nil
}

func generateSpecMarkdown(title, description string, questions []planningQuestionRow) string {
	var b strings.Builder

	b.WriteString("# ")
	b.WriteString(title)
	b.WriteString("\n\n**Status:** SPEC LOCKED ✅\n\n")

	if description != "" {
		b.WriteString("## Original Request\n")
		b.WriteString(description)
		b.WriteString("\n\n")
	}

	// Group by category
	catLabels := map[string]string{
		"goal":        "🎯 Goal & Success Criteria",
		"audience":    "👥 Target Audience",
		"scope":       "📋 Scope",
		"design":      "🎨 Design & Visual",
		"content":     "📝 Content",
		"technical":   "⚙️ Technical Requirements",
		"timeline":    "📅 Timeline",
		"constraints": "⚠️ Constraints",
	}

	catOrder := []string{"goal", "audience", "scope", "design", "content", "technical", "timeline", "constraints"}
	groups := map[string][]struct {
		Question string
		Answer   string
	}{}
	var seenCats []string

	for _, q := range questions {
		if _, ok := groups[q.Category]; !ok {
			seenCats = append(seenCats, q.Category)
		}
		groups[q.Category] = append(groups[q.Category], struct {
			Question string
			Answer   string
		}{q.Question, q.Answer})
	}

	// Merge seenCats into catOrder, preserving order
	allCats := catOrder
	for _, c := range seenCats {
		found := false
		for _, existing := range allCats {
			if existing == c {
				found = true
				break
			}
		}
		if !found {
			allCats = append(allCats, c)
		}
	}

	for _, cat := range allCats {
		qs, ok := groups[cat]
		if !ok || len(qs) == 0 {
			continue
		}
		label := cat
		if l, ok := catLabels[cat]; ok {
			label = l
		}
		b.WriteString("## ")
		b.WriteString(label)
		b.WriteString("\n\n")

		for _, q := range qs {
			b.WriteString("**")
			b.WriteString(q.Question)
			b.WriteString("**\n> ")
			b.WriteString(q.Answer)
			b.WriteString("\n\n")
		}
	}

	b.WriteString("---\n*Spec locked*\n")
	return b.String()
}