/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as McRouteImport } from './routes/mc'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LauncherSetupRouteImport } from './routes/launcher-setup'
import { Route as LauncherLoginRouteImport } from './routes/launcher-login'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as ChannelsRouteRouteImport } from './routes/channels/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McWorkspacesRouteImport } from './routes/mc/workspaces'
import { Route as McTasksRouteImport } from './routes/mc/tasks'
import { Route as McAgentsRouteImport } from './routes/mc/agents'
import { Route as McActivityRouteImport } from './routes/mc/activity'
import { Route as ConfigRawRouteImport } from './routes/config.raw'
import { Route as ChannelsNameRouteImport } from './routes/channels/$name'
import { Route as AgentToolsRouteImport } from './routes/agent/tools'
import { Route as AgentSkillsRouteImport } from './routes/agent/skills'
import { Route as AgentHubRouteImport } from './routes/agent/hub'
import { Route as McAutopilotIndexRouteImport } from './routes/mc/autopilot/index'
import { Route as McAutopilotProductIdRouteImport } from './routes/mc/autopilot/$productId'

const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const McRoute = McRouteImport.update({
  id: '/mc',
  path: '/mc',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherSetupRoute = LauncherSetupRouteImport.update({
  id: '/launcher-setup',
  path: '/launcher-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherLoginRoute = LauncherLoginRouteImport.update({
  id: '/launcher-login',
  path: '/launcher-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRouteRoute = ChannelsRouteRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McWorkspacesRoute = McWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => McRoute,
} as any)
const McTasksRoute = McTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => McRoute,
} as any)
const McAgentsRoute = McAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => McRoute,
} as any)
const McActivityRoute = McActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => McRoute,
} as any)
const ConfigRawRoute = ConfigRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ConfigRoute,
} as any)
const ChannelsNameRoute = ChannelsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ChannelsRouteRoute,
} as any)
const AgentToolsRoute = AgentToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSkillsRoute = AgentSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentRoute,
} as any)
const AgentHubRoute = AgentHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AgentRoute,
} as any)
const McAutopilotIndexRoute = McAutopilotIndexRouteImport.update({
  id: '/autopilot/',
  path: '/autopilot/',
  getParentRoute: () => McRoute,
} as any)
const McAutopilotProductIdRoute = McAutopilotProductIdRouteImport.update({
  id: '/autopilot/$productId',
  path: '/autopilot/$productId',
  getParentRoute: () => McRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/mc': typeof McRouteWithChildren
  '/models': typeof ModelsRoute
  '/agent/hub': typeof AgentHubRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/mc/activity': typeof McActivityRoute
  '/mc/agents': typeof McAgentsRoute
  '/mc/tasks': typeof McTasksRoute
  '/mc/workspaces': typeof McWorkspacesRoute
  '/mc/autopilot/$productId': typeof McAutopilotProductIdRoute
  '/mc/autopilot/': typeof McAutopilotIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/mc': typeof McRouteWithChildren
  '/models': typeof ModelsRoute
  '/agent/hub': typeof AgentHubRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/mc/activity': typeof McActivityRoute
  '/mc/agents': typeof McAgentsRoute
  '/mc/tasks': typeof McTasksRoute
  '/mc/workspaces': typeof McWorkspacesRoute
  '/mc/autopilot/$productId': typeof McAutopilotProductIdRoute
  '/mc/autopilot': typeof McAutopilotIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/mc': typeof McRouteWithChildren
  '/models': typeof ModelsRoute
  '/agent/hub': typeof AgentHubRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/mc/activity': typeof McActivityRoute
  '/mc/agents': typeof McAgentsRoute
  '/mc/tasks': typeof McTasksRoute
  '/mc/workspaces': typeof McWorkspacesRoute
  '/mc/autopilot/$productId': typeof McAutopilotProductIdRoute
  '/mc/autopilot/': typeof McAutopilotIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/mc'
    | '/models'
    | '/agent/hub'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
    | '/mc/activity'
    | '/mc/agents'
    | '/mc/tasks'
    | '/mc/workspaces'
    | '/mc/autopilot/$productId'
    | '/mc/autopilot/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/mc'
    | '/models'
    | '/agent/hub'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
    | '/mc/activity'
    | '/mc/agents'
    | '/mc/tasks'
    | '/mc/workspaces'
    | '/mc/autopilot/$productId'
    | '/mc/autopilot'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/mc'
    | '/models'
    | '/agent/hub'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
    | '/mc/activity'
    | '/mc/agents'
    | '/mc/tasks'
    | '/mc/workspaces'
    | '/mc/autopilot/$productId'
    | '/mc/autopilot/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRouteRoute: typeof ChannelsRouteRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  ConfigRoute: typeof ConfigRouteWithChildren
  CredentialsRoute: typeof CredentialsRoute
  LauncherLoginRoute: typeof LauncherLoginRoute
  LauncherSetupRoute: typeof LauncherSetupRoute
  LogsRoute: typeof LogsRoute
  McRoute: typeof McRouteWithChildren
  ModelsRoute: typeof ModelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mc': {
      id: '/mc'
      path: '/mc'
      fullPath: '/mc'
      preLoaderRoute: typeof McRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-setup': {
      id: '/launcher-setup'
      path: '/launcher-setup'
      fullPath: '/launcher-setup'
      preLoaderRoute: typeof LauncherSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-login': {
      id: '/launcher-login'
      path: '/launcher-login'
      fullPath: '/launcher-login'
      preLoaderRoute: typeof LauncherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mc/workspaces': {
      id: '/mc/workspaces'
      path: '/workspaces'
      fullPath: '/mc/workspaces'
      preLoaderRoute: typeof McWorkspacesRouteImport
      parentRoute: typeof McRoute
    }
    '/mc/tasks': {
      id: '/mc/tasks'
      path: '/tasks'
      fullPath: '/mc/tasks'
      preLoaderRoute: typeof McTasksRouteImport
      parentRoute: typeof McRoute
    }
    '/mc/agents': {
      id: '/mc/agents'
      path: '/agents'
      fullPath: '/mc/agents'
      preLoaderRoute: typeof McAgentsRouteImport
      parentRoute: typeof McRoute
    }
    '/mc/activity': {
      id: '/mc/activity'
      path: '/activity'
      fullPath: '/mc/activity'
      preLoaderRoute: typeof McActivityRouteImport
      parentRoute: typeof McRoute
    }
    '/config/raw': {
      id: '/config/raw'
      path: '/raw'
      fullPath: '/config/raw'
      preLoaderRoute: typeof ConfigRawRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/channels/$name': {
      id: '/channels/$name'
      path: '/$name'
      fullPath: '/channels/$name'
      preLoaderRoute: typeof ChannelsNameRouteImport
      parentRoute: typeof ChannelsRouteRoute
    }
    '/agent/tools': {
      id: '/agent/tools'
      path: '/tools'
      fullPath: '/agent/tools'
      preLoaderRoute: typeof AgentToolsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/skills': {
      id: '/agent/skills'
      path: '/skills'
      fullPath: '/agent/skills'
      preLoaderRoute: typeof AgentSkillsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/hub': {
      id: '/agent/hub'
      path: '/hub'
      fullPath: '/agent/hub'
      preLoaderRoute: typeof AgentHubRouteImport
      parentRoute: typeof AgentRoute
    }
    '/mc/autopilot/': {
      id: '/mc/autopilot/'
      path: '/autopilot'
      fullPath: '/mc/autopilot/'
      preLoaderRoute: typeof McAutopilotIndexRouteImport
      parentRoute: typeof McRoute
    }
    '/mc/autopilot/$productId': {
      id: '/mc/autopilot/$productId'
      path: '/autopilot/$productId'
      fullPath: '/mc/autopilot/$productId'
      preLoaderRoute: typeof McAutopilotProductIdRouteImport
      parentRoute: typeof McRoute
    }
  }
}

interface ChannelsRouteRouteChildren {
  ChannelsNameRoute: typeof ChannelsNameRoute
}

const ChannelsRouteRouteChildren: ChannelsRouteRouteChildren = {
  ChannelsNameRoute: ChannelsNameRoute,
}

const ChannelsRouteRouteWithChildren = ChannelsRouteRoute._addFileChildren(
  ChannelsRouteRouteChildren,
)

interface AgentRouteChildren {
  AgentHubRoute: typeof AgentHubRoute
  AgentSkillsRoute: typeof AgentSkillsRoute
  AgentToolsRoute: typeof AgentToolsRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentHubRoute: AgentHubRoute,
  AgentSkillsRoute: AgentSkillsRoute,
  AgentToolsRoute: AgentToolsRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface ConfigRouteChildren {
  ConfigRawRoute: typeof ConfigRawRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigRawRoute: ConfigRawRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

interface McRouteChildren {
  McActivityRoute: typeof McActivityRoute
  McAgentsRoute: typeof McAgentsRoute
  McTasksRoute: typeof McTasksRoute
  McWorkspacesRoute: typeof McWorkspacesRoute
  McAutopilotProductIdRoute: typeof McAutopilotProductIdRoute
  McAutopilotIndexRoute: typeof McAutopilotIndexRoute
}

const McRouteChildren: McRouteChildren = {
  McActivityRoute: McActivityRoute,
  McAgentsRoute: McAgentsRoute,
  McTasksRoute: McTasksRoute,
  McWorkspacesRoute: McWorkspacesRoute,
  McAutopilotProductIdRoute: McAutopilotProductIdRoute,
  McAutopilotIndexRoute: McAutopilotIndexRoute,
}

const McRouteWithChildren = McRoute._addFileChildren(McRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRouteRoute: ChannelsRouteRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  ConfigRoute: ConfigRouteWithChildren,
  CredentialsRoute: CredentialsRoute,
  LauncherLoginRoute: LauncherLoginRoute,
  LauncherSetupRoute: LauncherSetupRoute,
  LogsRoute: LogsRoute,
  McRoute: McRouteWithChildren,
  ModelsRoute: ModelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
